const gameActionTypes = {
  FILL_FIELD: 'FILL_FIELD',
  FILL_RANDOM: 'FILL_RANDOM',
  SET_SQUARE: 'SET_SQUARE',
  SET_GAME_STATUS: 'SET_GAME_STATUS',
  SET_CURRENT: 'SET_CURRENT',
  WRONG_ADD: 'WRONG_ADD',
  RIGHT_ADD: 'RIGHT_ADD',
  SET_GAME_RESULT: 'SET_GAME_RESULT',
  SET_COLUMNS: 'SET_COLUMNS',
  SET_ROWS: 'SET_ROWS',
  SET_NEW_TIME: 'SET_NEW_TIME',
  TURN_HARDMODE: 'TURN_HARDMODE',
  SET_RATING: 'SET_RATING',
  SET_LEVEL: 'SET_LEVEL',
}

export default gameActionTypes
